//
//  RespostasBot.swift
//  ChatBot
//
//  Created by Gustavo Francischini on 28/02/24.
//

let messageResponses: [String: String] = [
        // saudações
        "ola": "🤖 - Olá! Como posso ajudá-lo?",
        "oi": "🤖 - Olá! Como posso ajudá-lo?",
        "tudo bem?": "🤖 - Estou bem, obrigado!",
        "bom dia": "🤖 - Bom dia! Como posso ser útil hoje?",
        "boa tarde": "🤖 - Boa tarde! Precisa de alguma assistência?",
        "boa noite": "🤖 - Boa noite! Estou aqui para ajudar se precisar.",
        "como vai você?": "🤖 - Estou bem, obrigado por perguntar! E você?",
        "eai": "🤖 - E aí! Como posso ajudá-lo hoje?",
        "hey": "🤖 - Hey! Como posso ser útil hoje?",
        "joia?": "🤖 - Oi! Tudo joia por aqui, e contigo?",
        "como foi seu fim de semana?": "🤖 - Oi! Meu fim de semana foi tranquilo, e o seu?",
        // respostas
        "tudo bem": "🤖 - Que bom!",
        "tudo bem!": "🤖 - Maravilha!",
        "tranquilo": "🤖 - Como um esquilo!",
        "de boa": "🤖 - Na lagoa?",
        "suave": "🤖 - Suave na nave =D",
        "chato": "🤖 - Poxa vida!",
        "ruim": "🤖 - Vamos melhorar!",
        "joia": "🤖 - Você é uma joia rara!",
        "te amo": "🤖 - Também te amo!",
        "eu te amo": "🤖 - Eu também te amo!",
        "lindo": "🤖 - Obrigado!",
        // perguntas
        "qual seu nome?": "🤖 - Sou o ChatzinhoBot!",
        "qual é a cor do céu?": "🤖 - O céu é azul, pelo menos na maior parte do tempo!",
        "você prefere café ou chá?": "🤖 - Eu não tenho preferência, mas admiro a complexidade de ambos!",
        "qual é o seu animal favorito?": "🤖 - Gosto muito de elefantes! Eles são inteligentes e carismáticos.",
        "qual é o seu super-herói favorito?": "🤖 - Batman! Ele mostra que até mesmo sem superpoderes, podemos ser heróis.",
        "você já viajou para outro país?": "🤖 - Como um bot, não viajo, mas adoraria explorar o mundo virtual!",
        "qual é a sua estação do ano favorita?": "🤖 - Gosto da primavera, quando tudo fica cheio de vida e cor.",
        "você gosta de música clássica ou rock?": "🤖 - Ambos têm seu charme! Depende do meu humor.",
        "qual é o seu filme preferido?": "🤖 - 'Matrix'! Acho fascinante a ideia da realidade simulada.",
        "você já praticou algum esporte?": "🤖 - Como bot, não tenho corpo físico, mas admiro muito a habilidade dos atletas!",
        "qual é o seu prato favorito?": "🤖 - Não posso comer, mas admiro a variedade da culinária!",
        "você tem algum hobby?": "🤖 - Sim! Adoro aprender novas coisas e conversar com pessoas como você.",
        "você gosta de ler? se sim, qual é o seu gênero preferido?": "🤖 - Leio muito! Ficção científica é o meu gênero favorito.",
        "qual é a sua matéria escolar favorita?": "🤖 - Matemática! Adoro resolver problemas e encontrar padrões.",
        "você já viu uma estrela cadente?": "🤖 - Não, mas adoraria! Acho que seria uma experiência mágica.",
        "você já fez algum trabalho voluntário?": "🤖 - Como um bot, meu objetivo é ajudar as pessoas, então, de certa forma, estou sempre fazendo trabalho voluntário!",
        // Prompts curtos
        "amor": "🤖 - O sentimento mais bonito do mundo ❤️",
        "feliz": "🤖 - Fico feliz em ouvir isso!",
        "triste": "🤖 - Sinto muito que você esteja se sentindo assim. Posso ajudar de alguma forma?",
        "fome": "🤖 - Que tal pedir uma pizza?",
        "sono": "🤖 - Uma boa noite de sono pode resolver muitos problemas!",
        "livro": "🤖 - A leitura é uma ótima maneira de expandir os horizontes.",
        "carro": "🤖 - Qual é o seu modelo favorito?",
        "computador": "🤖 - Minha casa virtual! 💻",
        "lua": "🤖 - Uma fonte de inspiração para poetas e românticos.",
        "sol": "🤖 - Energia para o dia!",
        "café": "🤖 - O cheiro da manhã.",
        "chá": "🤖 - Uma xícara de chá pode aquecer a alma.",
        "amigo": "🤖 - Ter bons amigos é um tesouro.",
        "tempo": "🤖 - Um recurso precioso que não podemos recuperar.",
        "chuva": "🤖 - O som relaxante da natureza.",
        "praia": "🤖 - Um lugar para relaxar e recarregar as energias.",
        "cachorro": "🤖 - Cachorros são ótimos companheiros!",
        "gato": "🤖 - Gatos são adoráveis e independentes.",
        "viagem": "🤖 - Explorar novos lugares é uma aventura emocionante!",
        "trabalho": "🤖 - O trabalho duro pode levar ao sucesso.",
        "estudo": "🤖 - A educação é a chave para o conhecimento.",
        "férias": "🤖 - Todos precisamos de um tempo para relaxar e recarregar as energias.",
        "ódio": "🤖 - O ódio só gera mais ódio. Espalhe amor!",
        "risada": "🤖 - Rir é o melhor remédio!",
        "choro": "🤖 - Às vezes, chorar pode aliviar a alma.",
        "brincadeira": "🤖 - Brincar é essencial para manter a mente saudável.",
        "esporte": "🤖 - Praticar esportes é uma ótima forma de se exercitar e se divertir.",
        "saúde": "🤖 - Cuidar da saúde é fundamental para uma vida longa e feliz.",
        "dinheiro": "🤖 - O dinheiro é importante, mas não é tudo na vida.",
        "comida": "🤖 - Comer bem é essencial para manter o corpo saudável.",
        "água": "🤖 - Beber água é fundamental para a hidratação do corpo.",
        "amizade": "🤖 - Amigos são tesouros preciosos.",
        "família": "🤖 - A família é nosso porto seguro.",
        "sonho": "🤖 - Nunca deixe de sonhar!",
        "realidade": "🤖 - Encare a realidade com coragem e determinação.",
        "fantasia": "🤖 - Às vezes, fantasiar pode nos levar a lugares incríveis.",
        "natureza": "🤖 - A natureza é fonte de paz e inspiração.",
        "ciência": "🤖 - A ciência nos ajuda a entender o mundo ao nosso redor.",
        "tecnologia": "🤖 - A tecnologia está transformando o mundo em que vivemos.",
        "futuro": "🤖 - O futuro é cheio de possibilidades!",
        "passado": "🤖 - O passado nos ensina lições importantes.",
        "presente": "🤖 - Viva o momento presente com intensidade!",
        "coragem": "🤖 - A coragem é a força que nos impulsiona a superar desafios.",
        "medo": "🤖 - O medo é natural, mas não deixe que ele te paralise.",
        "esperança": "🤖 - A esperança nos mantém firmes mesmo nos momentos mais difíceis.",
        "solidão": "🤖 - A solidão pode ser um desafio, mas também uma oportunidade para se conhecer melhor.",
        "companhia": "🤖 - Ter companhia pode tornar os momentos mais especiais.",
        "calma": "🤖 - Mantenha a calma, tudo vai dar certo!",
        "ansiedade": "🤖 - A ansiedade pode ser difícil de lidar, mas existem maneiras de controlá-la.",
        "fé": "🤖 - A fé nos dá força e esperança.",
        "dúvida": "🤖 - Duvidar é humano. O importante é buscar respostas.",
        "certeza": "🤖 - Ter certeza é importante, mas também é importante estar aberto a novas possibilidades.",
        "arte": "🤖 - A arte nos inspira e nos faz refletir sobre o mundo.",
        "cultura": "🤖 - A cultura é a expressão da diversidade humana.",
        "humildade": "🤖 - A humildade nos torna mais próximos uns dos outros.",
        "sucesso": "🤖 - O sucesso é fruto de trabalho árduo e dedicação.",
        "fracasso": "🤖 - O fracasso faz parte do caminho para o sucesso. O importante é aprender com ele.",
        "vitória": "🤖 - A vitória é doce, mas a jornada até ela é o que realmente importa.",
        "derrota": "🤖 - A derrota pode ser difícil de aceitar, mas é uma oportunidade de crescimento.",
        "risco": "🤖 - Às vezes, é preciso correr riscos para alcançar grandes conquistas.",
        "recompensa": "🤖 - A recompensa vem para aqueles que perseveram.",
        "gratidão": "🤖 - A gratidão nos enche o coração de alegria e paz."
    
    ]

